<?php

return array(
	'php' => 'PHP',
	'javascript' => 'Javascript',
	'python' => 'Python',
	'clojure' => 'Closure',
	'coffee' => 'Coffeescript',
	'css' => 'CSS',
	'dart' => 'Dart',
	'django' => 'Django',
	'haml' => 'HAML',
	'html' => 'HTML',
	'less' => 'Less CSS',
	'objectivec' => 'Obj-C',
	'perl' => 'Perl',
	'ruby' => 'Ruby',
	'sass' => 'Sass',
	'scala' => 'Scala',
	'scss' =>' SCSS',
	'sql' => 'SQL',
	'xml' => 'XML',
	'yaml' => 'YAML',
	'text' => 'Plain Text',
);